version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80  
     volumes:
         - ./php_code/php-e-commerce/:/var/www/html/
   php:
     build: ./php_code/php-e-commerce/
     expose:
       - 9000
     volumes:
        - ./php_code/php-e-commerce/:/var/www/html/
   db:    
      image: mariadb  
      volumes: 
        -    mysql-data:/var/lib/mysql
      environment:  
       MYSQL_ROOT_PASSWORD: mariadb
       MYSQL_DATABASE: ecomdb 
volumes:
    mysql-data:
